- "StoryData/**"
- "**/ScenarioModelCodes-AutoCreated.json"
- "**/StageNode*"
- "**/*StageNode*"
- "**/*StageNode*/**"
- "rpg-loc-dialogue-*"
- "rpg-loc-location-*"
- "rpg-loc-narration-*"
- "rpg-loc-npc-*"
- "rpg-loc-player-*"
- "rpg-loc-quest-*"
- "rpg-loc-swarm-*"
- "BattleSpeechBubbleDlg-*"
- "BattleAnnouncerDlg/**"
- "BgmLyrics_*"
- "BattleHint.json"
- "BattleHint_AbnorBattle.json"
- "BattleHint_NormalBattle.json"
- "BattleSpeechBubbleDlg*"
- "StoryTheater*"
- "AbnormalityGuides*"