name: Release Rainbus Toolbox (Self-hosted Linux)

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ["self-hosted", "Linux", "X64"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add preinstalled .NET to PATH
        run: echo "$HOME/dotnet:$HOME/dotnet/tools:$PATH" >> $GITHUB_PATH

      - name: Set version
        id: version
        run: |
          # Extract tag name
          VERSION="${GITHUB_REF##refs/tags/}"
          
          # Fallback for manual runs
          if [ -z "$VERSION" ]; then
            VERSION="0.0.0-local"
          fi
      
          # Remove leading 'v' if present
          VERSION="${VERSION#v}"
      
          # Replace any invalid characters with '-' (just in case)
          VERSION=$(echo "$VERSION" | tr -c '[:alnum:].+-' '-')
      
          # Remove trailing '-' if any
          VERSION="${VERSION%-}"
      
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Linux
        run: |
          dotnet publish -c Release -r linux-x64 --self-contained true \
            /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true \
            /p:AssemblyName=RainbusToolbox -o out/linux-x64
          chmod +x out/linux-x64/RainbusToolbox
          tar -czf RainbusToolbox-linux-x64-${VERSION}.tar.gz -C out/linux-x64 .

      - name: Build Windows
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true \
            /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true \
            /p:AssemblyName=RainbusToolbox -o out/win-x64
          (cd out/win-x64 && zip -r ../../RainbusToolbox-win-x64-${VERSION}.zip .)

      - name: Build macOS
        run: |
          dotnet publish -c Release -r osx-x64 --self-contained true \
            /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true \
            /p:AssemblyName=RainbusToolbox -o out/osx-x64
          chmod +x out/osx-x64/RainbusToolbox
          tar -czf RainbusToolbox-osx-x64-${VERSION}.tar.gz -C out/osx-x64 .

      - name: Upload release assets
        run: |
          gh release upload "$VERSION" RainbusToolbox-linux-x64-${VERSION}.tar.gz --clobber
          gh release upload "$VERSION" RainbusToolbox-win-x64-${VERSION}.zip --clobber
          gh release upload "$VERSION" RainbusToolbox-osx-x64-${VERSION}.tar.gz --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # <-- Use your PAT here

      - name: Update release notes
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_PAT }}          # <-- Must use PAT, not GITHUB_TOKEN
          body: |
            ## How to Run

            **Linux**  
            1. Download `RainbusToolbox-linux-x64-<version>.tar.gz`  
            2. Extract: `tar -xzf RainbusToolbox-linux-x64-<version>.tar.gz`  
            3. Run: `./RainbusToolbox`

            **Windows**  
            1. Download `RainbusToolbox-win-x64-<version>.zip`  
            2. Extract the archive  
            3. Double-click `RainbusToolbox.exe`

            **macOS**  
            1. Download `RainbusToolbox-osx-x64-<version>.tar.gz`  
            2. Extract: `tar -xzf RainbusToolbox-osx-x64-<version>.tar.gz`  
            3. Run: `./RainbusToolbox`  
               (May require *System Preferences → Security & Privacy*)
