name: Release Rainbus Toolbox

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Set version
        id: version
        run: |
          VERSION="${GITHUB_REF##refs/tags/}"
          if [ -z "$VERSION" ]; then
            VERSION="0.0.0-local"
          fi
          VERSION="${VERSION#v}"
          VERSION=$(echo "$VERSION" | tr -c '[:alnum:].+-' '-')
          VERSION="${VERSION%-}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Linux
        run: |
          dotnet publish -c Release -r linux-x64 --self-contained true \
            /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true \
            /p:AssemblyName=RainbusToolbox -o out/linux-x64
          chmod +x out/linux-x64/RainbusToolbox
          tar -czf RainbusToolbox-linux-x64-${VERSION}.tar.gz -C out/linux-x64 .

      - name: Build Windows
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true \
            /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true \
            /p:AssemblyName=RainbusToolbox -o out/win-x64
          (cd out/win-x64 && zip -r ../../RainbusToolbox-win-x64-${VERSION}.zip .)

      - name: Build macOS
        run: |
          dotnet publish -c Release -r osx-x64 --self-contained true \
            /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true \
            /p:AssemblyName=RainbusToolbox -o out/osx-x64
          chmod +x out/osx-x64/RainbusToolbox
          tar -czf RainbusToolbox-osx-x64-${VERSION}.tar.gz -C out/osx-x64 .

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh release upload "$VERSION" RainbusToolbox-linux-x64-${VERSION}.tar.gz --clobber
          gh release upload "$VERSION" RainbusToolbox-win-x64-${VERSION}.zip --clobber
          gh release upload "$VERSION" RainbusToolbox-osx-x64-${VERSION}.tar.gz --clobber
