name: Release Rainbus Toolbox

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            ext: zip
          - os: ubuntu-latest
            rid: linux-x64
            ext: tar.gz
          - os: macos-latest
            rid: osx-x64
            ext: tar.gz
    runs-on: ${{ matrix.os }}

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish app
        run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true /p:AssemblyName=RainbusToolbox -o out/${{ matrix.rid }}

      - name: Make binary executable (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: chmod +x out/${{ matrix.rid }}/RainbusToolbox

      - name: Package artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path out/${{ matrix.rid }}/* -DestinationPath RainbusToolbox-${{ matrix.rid }}-${{ github.event.release.tag_name }}.${{ matrix.ext }}

      - name: Package artifacts (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: tar -czf RainbusToolbox-${{ matrix.rid }}-${{ github.event.release.tag_name }}.${{ matrix.ext }} -C out/${{ matrix.rid }} .

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: RainbusToolbox-${{ matrix.rid }}-${{ github.event.release.tag_name }}.${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Append usage instructions to release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## How to Run

            **Windows**  
            1. Download `RainbusToolbox-win-x64-<version>.zip`  
            2. Extract the archive  
            3. Double-click `RainbusToolbox.exe`

            **Linux**  
            1. Download `RainbusToolbox-linux-x64-<version>.tar.gz`  
            2. Extract: `tar -xzf RainbusToolbox-linux-x64-<version>.tar.gz`  
            3. Run: `./RainbusToolbox`

            **macOS**  
            1. Download `RainbusToolbox-osx-x64-<version>.tar.gz`  
            2. Extract: `tar -xzf RainbusToolbox-osx-x64-<version>.tar.gz`  
            3. Run: `./RainbusToolbox`  
               (On first run, you may need to allow it in *System Preferences → Security & Privacy*)

            ---

            ## Как запустить

            **Windows**  
            1. Скачайте `RainbusToolbox-win-x64-<версия>.zip`  
            2. Распакуйте архив  
            3. Дважды кликните `RainbusToolbox.exe`

            **Linux**  
            1. Скачайте `RainbusToolbox-linux-x64-<версия>.tar.gz`  
            2. Распакуйте: `tar -xzf RainbusToolbox-linux-x64-<версия>.tar.gz`  
            3. Запустите: `./RainbusToolbox`

            **macOS**  
            1. Скачайте `RainbusToolbox-osx-x64-<версия>.tar.gz`  
            2. Распакуйте: `tar -xzf RainbusToolbox-osx-x64-<версия>.tar.gz`  
            3. Запустите: `./RainbusToolbox`  
               (При первом запуске, возможно, нужно будет разрешить запуск в *Системные настройки → Защита и безопасность*)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

