name: Release Rainbus Toolbox (Self-hosted Linux)

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ["self-hosted", "Linux", "X64"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET (user-local)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
        env:
          DOTNET_INSTALL_DIR: $HOME/.dotnet
          DOTNET_ROOT: $HOME/.dotnet

      - name: Add dotnet to PATH
        run: |
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "PATH=$HOME/.dotnet:$HOME/.dotnet/tools:$PATH" >> $GITHUB_ENV

      - name: Set version
        id: version
        run: |
          VERSION="${GITHUB_REF##refs/tags/}"
          if [ -z "$VERSION" ]; then
            VERSION="manual"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Linux
        run: |
          dotnet publish -c Release -r linux-x64 --self-contained true \
            /p:PublishSingleFile=true \
            /p:IncludeAllContentForSelfExtract=true \
            /p:AssemblyName=RainbusToolbox \
            -o out/linux-x64
          chmod +x out/linux-x64/RainbusToolbox
          tar -czf RainbusToolbox-linux-x64-${VERSION}.tar.gz -C out/linux-x64 .

      - name: Build Windows (zip on Linux)
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true \
            /p:PublishSingleFile=true \
            /p:IncludeAllContentForSelfExtract=true \
            /p:AssemblyName=RainbusToolbox \
            -o out/win-x64
          zip -r RainbusToolbox-win-x64-${VERSION}.zip out/win-x64/*

      - name: Build macOS
        run: |
          dotnet publish -c Release -r osx-x64 --self-contained true \
            /p:PublishSingleFile=true \
            /p:IncludeAllContentForSelfExtract=true \
            /p:AssemblyName=RainbusToolbox \
            -o out/osx-x64
          chmod +x out/osx-x64/RainbusToolbox
          tar -czf RainbusToolbox-osx-x64-${VERSION}.tar.gz -C out/osx-x64 .

      - name: Upload release assets
        run: |
          gh release upload "$VERSION" RainbusToolbox-linux-x64-${VERSION}.tar.gz
          gh release upload "$VERSION" RainbusToolbox-win-x64-${VERSION}.zip
          gh release upload "$VERSION" RainbusToolbox-osx-x64-${VERSION}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update release notes
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## How to Run

            **Linux**  
            1. Download `RainbusToolbox-linux-x64-<version>.tar.gz`  
            2. Extract: `tar -xzf RainbusToolbox-linux-x64-<version>.tar.gz`  
            3. Run: `./RainbusToolbox`

            **Windows**  
            1. Download `RainbusToolbox-win-x64-<version>.zip`  
            2. Extract the archive  
            3. Double-click `RainbusToolbox.exe`

            **macOS**  
            1. Download `RainbusToolbox-osx-x64-<version>.tar.gz`  
            2. Extract: `tar -xzf RainbusToolbox-osx-x64-<version>.tar.gz`  
            3. Run: `./RainbusToolbox`  
               (May require *System Preferences → Security & Privacy*)

            ---

            ## Как запустить

            **Linux**  
            1. Скачайте `RainbusToolbox-linux-x64-<версия>.tar.gz`  
            2. Распакуйте: `tar -xzf RainbusToolbox-linux-x64-<версия>.tar.gz`  
            3. Запустите: `./RainbusToolbox`

            **Windows**  
            1. Скачайте `RainbusToolbox-win-x64-<версия>.zip`  
            2. Распакуйте архив  
            3. Дважды кликните `RainbusToolbox.exe`

            **macOS**  
            1. Скачайте `RainbusToolbox-osx-x64-<версия>.tar.gz`  
            2. Распакуйте: `tar -xzf RainbusToolbox-osx-x64-<версия>.tar.gz`  
            3. Запустите: `./RainbusToolbox`  
               (При первом запуске, возможно, нужно будет разрешить запуск в *Системные настройки → Защита и безопасность*)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
